import { getRandomFile } from './avatar';

export const accounts = [
  {
    id: '1',
    username: 'byron',
    displayName: 'Byron Arclight',
    email: '1@gmail.com',
    password: '$2a$12$ixH0oPx0IwNquNZAfsbd..9yo1gh82UZqK7ICIQKl6HV//SXAlARS',
    blocked: false,
    avatar: getRandomFile('byronat445'),
    verified: true,
    followers: 1000,
    following: 1000,
    hasFeed: true,
  },
  {
    id: '2',
    username: 'yuna',
    displayName: 'Yuna',
    email: '2@gmail.com',
    password: '1',
    blocked: false,
    avatar: getRandomFile('yuna'),
    verified: true,
    followers: 1000,
    following: 1000,
    hasFeed: true,
  },
  {
    id: 'blocked',
    username: 'Blocked',
    email: 'blocked@gmail.com',
    password: '1',
    blocked: true,
    avatar: getRandomFile('blocked'),
    verified: true,
    followers: 1000,
    following: 1000,
    hasFeed: true,
  },
];
