import type { MomentPayload } from 'api';
import { getRandomFile } from './file';
import { faker } from '@faker-js/faker';

const MAX_FOLLOW_NUM = 70000;
const MAX_LIKE_NUM = 70000;
const MAX_COMMENT_NUM = 70000;
const MAX_REPOST_NUM = 100;

export const mockMoments: MomentPayload[] = [
  {
    id: 'fc9ceeb0-fc9e-4d0c-9efd-6b674d5de57d',
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GtQ6RRjb0AA0ZkV?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '0',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GrAW1FlXkAAgu1O?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GtbCig-bIAAqvrd?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraphs(),
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gdtc9TWWYAA7DUE?format=jpg&name=4096x4096',
          aspectRatio: '1.91:1',
        },
        {
          id: '0',
          type: 'image',
          url: ' https://pbs.twimg.com/media/GX4zYoXaUAAb3hr?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GLpnRIWa8AAjVjt?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GKi4QHnboAAJWYV?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '0',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FvWhCjEakAAeQ6C?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '0',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
          aspectRatio: '1.91:1',
        },
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgHsZ5vakAAz5jI?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'video',
          url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GHv15bhbwAAXQlJ?format=jpg&name=4096x4096',
          aspectRatio: '1:1',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/F1IgZYmagAAbcwm?format=jpg&name=4096x4096',
          aspectRatio: '1:1',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GkUVxpLaIAAK5fK?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GDxlKAwbkAAEEH4?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FbT-hSnaMAITR81?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Fsh9DaOakAEL7B1?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgHsVFvbYAU2ZpA?format=jpg&name=large',
          aspectRatio: '1.91:1',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GTP4USoaYAMKWLD?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GoFJ8_PbYAAGVxY?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GmE2QNobcAE18qo?format=jpg&name=medium',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/F7_0tmmbMAAuv6G?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgHsRA8akAAeirJ?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '5',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GNVppwoakAA3Yxq?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GCpqzHQbwAABMGr?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/F-I4FN2bgAAbsbE?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '6',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GLGU7XDbEAADwGY?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgC22OAaMAAmA9I?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GCsUDkvaQAASmNU?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GllqHMLa4AATGzZ?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GlLNYbPbIAANJjZ?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '5',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gdm5F3mboAgSG_x?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Fi2-RJ9acAA7gYr?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GowgbJ9aIAADxvn?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Ghvkngoa0AAZBHM?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gj8UYDjbEAAVJeD?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GmkyyAnaEAA3K9v?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gj_e2lNbEAAWF9u?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GjMsVS9a0AA66Tb?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgLvSHibYAMCR1k?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gs_YbumagAAJKWg?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GtErX2oaIAAUAwM?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FtEzdouaQAARPKN?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GicHHmPaYAAfESg?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FkXOfZCaEAAR2pX?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FWHk8VgUIAANFcX?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FgzKZewagAAtE2G?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GN8JrXEaUAAvgQu?format=jpg&name=large',
          aspectRatio: '1.91:1',
        },
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GsxybX8bQAEQ8sW?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GjPNWTNb0AAZvar?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GgwpklCa0AA8MkD?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GKYSLwTaAAA7Uu9?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GEwApvjaMAAX2R6?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GnHpja0b0AAqHkB?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GiQ95fjbAAAL1ZK?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '5',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GjZDOyAa8AArPqh?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gryah3uXkAAvDtT?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GqpnuaVXAAAYrhH?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gs6j_R2bsAAL5cL?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GaARflpbEAAGnmH?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gc6Be8_bkAAXjoB?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GLiajEDboAAnccH?format=jpg&name=large',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GEmDEA9bcAAOfmP?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GHvc3k-bEAAtwWN?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FrZfFNvaQAAxuxq?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GFEigYqa0AAqYjf?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GHvc3k-bEAAtwWN?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.\nProin dignissim iaculis posuere. Nulla facilisi.\nIn ultrices, tortor quis ultrices pharetra, mauris tortor tempor turpis, sed pretium nisl nibh ac risus.\nSed elementum justo at arcu gravida aliquet et vitae nulla.',
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      text: faker.lorem.paragraph(),
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GSapLb6W0AADWqy?format=jpg&name=4096x4096',
          aspectRatio: '1.91:1',
        },
        {
          id: '2',
          type: 'image',
          url: 'https://pbs.twimg.com/media/Gt4gzd7XEAAXFTb?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '3',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GcZL3OJaAAATqcq?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
        {
          id: '4',
          type: 'image',
          url: 'https://pbs.twimg.com/media/F7Uf7RWaMAABcWG?format=jpg&name=large',
          aspectRatio: '1.91:1',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/GDdhBdYbwAA1BIE?format=jpg&name=large',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
  {
    id: faker.string.uuid(),
    user: {
      id: faker.string.uuid(),
      email: faker.internet.email(),
      username: faker.internet.username(),
      displayName: faker.person.fullName(),
      avatar: getRandomFile(faker.string.uuid()),
      followers: faker.number.int({ max: MAX_FOLLOW_NUM }),
      following: faker.number.int({ max: MAX_FOLLOW_NUM }),
      isFollowing: false,
      hasFeed: true,
    },
    post: {
      files: [
        {
          id: '1',
          type: 'image',
          url: 'https://pbs.twimg.com/media/FJrSq89UUAIGhDT?format=jpg&name=4096x4096',
          aspectRatio: '4:5',
        },
      ],
      likes: faker.number.int({ max: MAX_LIKE_NUM }),
      comments: faker.number.int({ max: MAX_COMMENT_NUM }),
      reposts: faker.number.int({ max: MAX_REPOST_NUM }),
      updatedAt: faker.date.past(),
      isLiked: false,
      isBookmarked: false,
    },
  },
];

// https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4
// https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4
// https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4
